# Generated by Django 4.1.7 on 2026-03-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_alias', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=50)),
                ('activity_type', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('performed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('hero_alias', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team_name', models.CharField(max_length=50)),
                ('universe', models.CharField(max_length=20)),
                ('weekly_goal', models.PositiveIntegerField(default=150)),
                ('total_points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('recorded_on', models.DateField()),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('universe', models.CharField(max_length=20)),
                ('motto', models.CharField(max_length=200)),
                ('captain', models.CharField(max_length=100)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('focus_area', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('coach_name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('recommended_for', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['title'],
            },
        ),
    ]
