# Generated by Django 4.1.7 on 2026-03-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['category', 'rank']},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user_email'], name='activities_user_em_5ea6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['team_name'], name='activities_team_na_22dff3_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessuser',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessuser',
            index=models.Index(fields=['team_name'], name='users_team_na_74c099_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('category', 'rank', 'display_name'), name='unique_leaderboard_entry'),
        ),
    ]
